FROM postgis/postgis:17-3.4

# Copy custom PostgreSQL configs
COPY postgresql.conf /etc/postgresql/postgresql.conf
COPY pg_hba.conf /etc/postgresql/pg_hba.conf

# Install pgvector and timescaledb
RUN apt-get update && apt-get install -y \
    postgresql-17-pgvector \
    postgresql-17-timescaledb \
    && rm -rf /var/lib/apt/lists/*
